repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: ["pyproject"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: flake8
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: bash -c 'pdm run python -m pytest tests'
        args: ['-p "*_test.py"']
        pass_filenames: false
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
      additional_dependencies: ["pyproject"]
      args: [--line-length=120]
      language_version: python3.10
